# wrangler.toml
name = "tw-api"
compatibility_date = "2024-09-23"   # 或更新
compatibility_flags = [ "nodejs_compat" ] # <--- 确保这个在这里

main = "./dist/worker.js"

[[d1_databases]]
binding = "DB"
database_name = "library"
database_id = "13cdef99-aa9e-4f12-9e7b-14ace0d5c92d"

[build]
command = "npm ci && npm run build"
watch_dir = "src"

[observability]
enabled = true