# wrangler.toml
name = "tw-api"
# compatibility_date = "2024-03-01" # 更新到或晚于 2024-09-23
compatibility_date = "2024-09-23"   # 或使用一个最新的日期，例如 "2024-04-05"

# 添加 nodejs_compat 标志
compatibility_flags = [ "nodejs_compat" ]

main = "./dist/worker.js"

[[d1_databases]]
binding = "DB"
database_name = "library"
database_id = "13cdef99-aa9e-4f12-9e7b-14ace0d5c92d"

[build]
command = "npm ci && npm run build"
watch_dir = "src"

[observability]
enabled = true